server:
  port: 8080
  host: "0.0.0.0"
  address: ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "123456"
  database: "ai_translate"
  charset: "utf8mb4"
  default:
    link: "mysql:root:123456@tcp(127.0.0.1:3306)/ai_translate"
    debug: true

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

rabbitmq:
  host: "localhost"
  port: 5672
  username: "guest"
  password: "guest"
  vhost: "/"
  exchange:
    name: "task_exchange"
    type: "direct"
    durable: true
  queues:
    content_generation:
      name: "content_generation"
      durable: true
    translation:
      name: "translation"
      durable: true

logger:
  level: "info"
  path: "logs"
  filename: "app.log"

jwt:
  secret: "your-jwt-secret"
  expire: 86400 # 24小时

aes:
  key: "your-aes-key-32bytes"

ratelimit:
  enabled: true
  rate: 100
  burst: 200

file:
  upload:
    path: "uploads"
    maxSize: 10485760 # 10MB
    allowedTypes:
      - "image/jpeg"
      - "image/png"
      - "image/gif"
      - "application/pdf"
      - "text/plain"

oss:
  type: "local" # local, aliyun, qiniu
  local:
    path: "uploads"
  aliyun:
    endpoint: "oss-cn-hangzhou.aliyuncs.com"
    accessKeyId: "your-access-key-id"
    accessKeySecret: "your-access-key-secret"
    bucket: "your-bucket"
  qiniu:
    endpoint: "http://cdn.example.com"
    accessKey: "your-access-key"
    secretKey: "your-secret-key"
    bucket: "your-bucket"

queue:
  redis:
    address: "127.0.0.1:6379"
    db: 2
  worker:
    numWorkers: 5
    maxRetries: 3

ai:
  openai:
    apiKey: "your-openai-api-key"
    model: "gpt-3.5-turbo"
    maxTokens: 2000
    temperature: 0.7
    timeout: 30
  gemini:
    apiKey: "your-gemini-api-key"
    model: "gemini-pro"
    timeout: 30 