version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    environment:
      - GF_GCFG_FILE=/app/manifest/config/config.yaml
    volumes:
      - ./:/app
    networks:
      - ai-translate-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=ai_translate
    volumes:
      - mysql-data:/var/lib/mysql
      - ./manifest/sql:/docker-entrypoint-initdb.d
    networks:
      - ai-translate-network

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ai-translate-network

  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
    volumes:
      - ./web/dist:/usr/share/nginx/html
      - ./manifest/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - ai-translate-network

volumes:
  mysql-data:
  redis-data:

networks:
  ai-translate-network:
    driver: bridge 